services:
  postgres:
    image: postgres:16-alpine
    container_name: verta-postgres
    environment:
      POSTGRES_DB: verta
      POSTGRES_USER: verta_user
      POSTGRES_PASSWORD: verta_password
    ports:
      - '25001:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U verta_user -d verta']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: verta-redis
    ports:
      - '25002:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: ./backend
      target: dev
    container_name: verta-app
    ports:
      - '25000:25000'
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./_data:/data
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DOCKERIZED=true
      - PORT=25000
      - DATABASE_URL=postgresql://verta_user:verta_password@postgres:5432/verta
      - DATABASE_POOL_SIZE=10
      - LOG_LEVEL=debug
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm run dev
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
