{{- if .Values.ml.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "verta.fullname" . }}-ml
  labels:
    {{- include "verta.labels" . | nindent 4 }}
    app.kubernetes.io/component: ml
spec:
  type: {{ .Values.ml.service.type }}
  ports:
    - port: {{ .Values.ml.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "verta.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ml
{{- end }}