name: Docker Build and Push

on:
  workflow_call:
    inputs:
      push:
        description: 'Whether to push images to registry'
        required: false
        type: boolean
        default: false
      tag-suffix:
        description: 'Additional tag suffix (e.g., pr-123, branch-name)'
        required: false
        type: string
        default: ''

env:
  REGISTRY: ghcr.io
  
jobs:
  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        service:
          - name: backend
            context: .
            dockerfile: ./backend/Dockerfile
            image: verta-backend
          - name: frontend  
            context: .
            dockerfile: ./frontend/Dockerfile
            image: verta-frontend
            build-args: |
              NEXT_PUBLIC_TENANT_SLUG=docker-build
          - name: ml-service
            context: ./python-ml-service
            dockerfile: ./python-ml-service/Dockerfile
            image: verta-ml-service
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
      
      - name: Log in to Container Registry
        if: inputs.push
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.service.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ inputs.tag-suffix }},enable=${{ inputs.tag-suffix != '' }}
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          platforms: linux/amd64
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.service.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service.name }}
          build-args: ${{ matrix.service.build-args }}
      
      - name: Image Summary
        run: |
          echo "### Docker Build Summary for ${{ matrix.service.name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Image**: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.service.image }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Push**: ${{ inputs.push && 'Yes' || 'No (dry run)' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tags**:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY